/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AudioMetadata = IDL.Record({
  'id' : IDL.Text,
  'isApproved' : IDL.Bool,
  'uploadedFrom' : IDL.Variant({
    'Studio' : IDL.Null,
    'CreatorZone' : IDL.Null,
  }),
  'duration' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'ownerPrincipal' : IDL.Principal,
});
export const Profile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'subscription' : IDL.Bool,
  'role' : UserRole,
});
export const AudioSubmissionInput = IDL.Record({
  'id' : IDL.Text,
  'uploadedFrom' : IDL.Variant({
    'Studio' : IDL.Null,
    'CreatorZone' : IDL.Null,
  }),
  'duration' : IDL.Nat,
  'isPremium' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveSubmission' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIsArtist' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllApprovedAudio' : IDL.Func([], [IDL.Vec(AudioMetadata)], ['query']),
  'getAllArtistProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getApprovedAudio' : IDL.Func([IDL.Text], [AudioMetadata], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingSubmissions' : IDL.Func([], [IDL.Vec(AudioMetadata)], ['query']),
  'getProfileByPrincipal' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectSubmission' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'searchArtists' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'submitAudioForApproval' : IDL.Func([AudioSubmissionInput], [], []),
  'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AudioMetadata = IDL.Record({
    'id' : IDL.Text,
    'isApproved' : IDL.Bool,
    'uploadedFrom' : IDL.Variant({
      'Studio' : IDL.Null,
      'CreatorZone' : IDL.Null,
    }),
    'duration' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'ownerPrincipal' : IDL.Principal,
  });
  const Profile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'subscription' : IDL.Bool,
    'role' : UserRole,
  });
  const AudioSubmissionInput = IDL.Record({
    'id' : IDL.Text,
    'uploadedFrom' : IDL.Variant({
      'Studio' : IDL.Null,
      'CreatorZone' : IDL.Null,
    }),
    'duration' : IDL.Nat,
    'isPremium' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveSubmission' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIsArtist' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllApprovedAudio' : IDL.Func([], [IDL.Vec(AudioMetadata)], ['query']),
    'getAllArtistProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getApprovedAudio' : IDL.Func([IDL.Text], [AudioMetadata], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingSubmissions' : IDL.Func([], [IDL.Vec(AudioMetadata)], ['query']),
    'getProfileByPrincipal' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectSubmission' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'searchArtists' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
    'submitAudioForApproval' : IDL.Func([AudioSubmissionInput], [], []),
    'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };