/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioMetadata {
  'id' : string,
  'isApproved' : boolean,
  'uploadedFrom' : { 'Studio' : null } |
    { 'CreatorZone' : null },
  'duration' : bigint,
  'isPremium' : boolean,
  'ownerPrincipal' : Principal,
}
export interface AudioSubmissionInput {
  'id' : string,
  'uploadedFrom' : { 'Studio' : null } |
    { 'CreatorZone' : null },
  'duration' : bigint,
  'isPremium' : boolean,
}
export interface Profile {
  'displayName' : string,
  'subscription' : boolean,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveSubmission' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIsArtist' : ActorMethod<[], boolean>,
  'getAllApprovedAudio' : ActorMethod<[], Array<AudioMetadata>>,
  'getAllArtistProfiles' : ActorMethod<[], Array<Profile>>,
  'getApprovedAudio' : ActorMethod<[string], AudioMetadata>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingSubmissions' : ActorMethod<[], Array<AudioMetadata>>,
  'getProfileByPrincipal' : ActorMethod<[Principal], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectSubmission' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, boolean], undefined>,
  'searchArtists' : ActorMethod<[string], Array<[Principal, Profile]>>,
  'submitAudioForApproval' : ActorMethod<[AudioSubmissionInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];