/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Profile {
    displayName: string;
    subscription: boolean;
    role: UserRole;
}
export interface AudioMetadata {
    id: string;
    isApproved: boolean;
    uploadedFrom: Variant_Studio_CreatorZone;
    duration: bigint;
    isPremium: boolean;
    ownerPrincipal: Principal;
}
export interface AudioSubmissionInput {
    id: string;
    uploadedFrom: Variant_Studio_CreatorZone;
    duration: bigint;
    isPremium: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Studio_CreatorZone {
    Studio = "Studio",
    CreatorZone = "CreatorZone"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveSubmission(submissionId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkIsArtist(): Promise<boolean>;
    getAllApprovedAudio(): Promise<Array<AudioMetadata>>;
    getAllArtistProfiles(): Promise<Array<Profile>>;
    getApprovedAudio(audioId: string): Promise<AudioMetadata>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPendingSubmissions(): Promise<Array<AudioMetadata>>;
    getProfileByPrincipal(principal: Principal): Promise<Profile>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectSubmission(submissionId: string): Promise<void>;
    saveCallerUserProfile(displayName: string, subscription: boolean): Promise<void>;
    searchArtists(search: string): Promise<Array<[Principal, Profile]>>;
    submitAudioForApproval(input: AudioSubmissionInput): Promise<void>;
}
import type { AudioMetadata as _AudioMetadata, AudioSubmissionInput as _AudioSubmissionInput, Profile as _Profile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveSubmission(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSubmission(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIsArtist(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIsArtist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIsArtist();
            return result;
        }
    }
    async getAllApprovedAudio(): Promise<Array<AudioMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedAudio();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedAudio();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArtistProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtistProfiles();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtistProfiles();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedAudio(arg0: string): Promise<AudioMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedAudio(arg0);
                return from_candid_AudioMetadata_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedAudio(arg0);
            return from_candid_AudioMetadata_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingSubmissions(): Promise<Array<AudioMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSubmissions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSubmissions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByPrincipal(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByPrincipal(arg0);
                return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByPrincipal(arg0);
            return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectSubmission(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSubmission(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async searchArtists(arg0: string): Promise<Array<[Principal, Profile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArtists(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArtists(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAudioForApproval(arg0: AudioSubmissionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAudioForApproval(to_candid_AudioSubmissionInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAudioForApproval(to_candid_AudioSubmissionInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AudioMetadata_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioMetadata): AudioMetadata {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isApproved: boolean;
    uploadedFrom: {
        Studio: null;
    } | {
        CreatorZone: null;
    };
    duration: bigint;
    isPremium: boolean;
    ownerPrincipal: Principal;
}): {
    id: string;
    isApproved: boolean;
    uploadedFrom: Variant_Studio_CreatorZone;
    duration: bigint;
    isPremium: boolean;
    ownerPrincipal: Principal;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        uploadedFrom: from_candid_variant_n6(_uploadFile, _downloadFile, value.uploadedFrom),
        duration: value.duration,
        isPremium: value.isPremium,
        ownerPrincipal: value.ownerPrincipal
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    subscription: boolean;
    role: _UserRole;
}): {
    displayName: string;
    subscription: boolean;
    role: UserRole;
} {
    return {
        displayName: value.displayName,
        subscription: value.subscription,
        role: from_candid_UserRole_n10(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _Profile]): [Principal, Profile] {
    return [
        value[0],
        from_candid_Profile_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Studio: null;
} | {
    CreatorZone: null;
}): Variant_Studio_CreatorZone {
    return "Studio" in value ? Variant_Studio_CreatorZone.Studio : "CreatorZone" in value ? Variant_Studio_CreatorZone.CreatorZone : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _Profile]>): Array<[Principal, Profile]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AudioMetadata>): Array<AudioMetadata> {
    return value.map((x)=>from_candid_AudioMetadata_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AudioSubmissionInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioSubmissionInput): _AudioSubmissionInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    uploadedFrom: Variant_Studio_CreatorZone;
    duration: bigint;
    isPremium: boolean;
}): {
    id: string;
    uploadedFrom: {
        Studio: null;
    } | {
        CreatorZone: null;
    };
    duration: bigint;
    isPremium: boolean;
} {
    return {
        id: value.id,
        uploadedFrom: to_candid_variant_n17(_uploadFile, _downloadFile, value.uploadedFrom),
        duration: value.duration,
        isPremium: value.isPremium
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Studio_CreatorZone): {
    Studio: null;
} | {
    CreatorZone: null;
} {
    return value == Variant_Studio_CreatorZone.Studio ? {
        Studio: null
    } : value == Variant_Studio_CreatorZone.CreatorZone ? {
        CreatorZone: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
